# Generated by Django 5.1.3 on 2024-11-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_model', models.CharField(max_length=255)),
                ('year_release', models.CharField(max_length=255)),
                ('gearbox_model', models.CharField(max_length=255)),
                ('engine_model', models.CharField(max_length=255)),
                ('chassis_type', models.CharField(max_length=255)),
            ],
        ),
    ]
