# Generated by Django 5.1.3 on 2024-11-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Trucks',
        ),
    ]
